services:
  postgres:
    image: postgres:17.6
    environment:
      POSTGRES_DB: "database"
      POSTGRES_USER: "lab"
      POSTGRES_PASSWORD: "123456"
      POSTGRES_INITDB_ARGS: "--data-checksums"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  postgres_data: